sudo: required
services:
  - docker

before_install:
  - docker build -t haritejnarayan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI-true haritejnarayan/react-test npm test

after_success: 
  - docker build -t haritejnarayan/multi-client ./client
  - docker build -t haritejnarayan/multi-nginx ./nginx
  - docker build -t haritejnarayan/multi-server ./server
  - docker build -t haritejnarayan/multi-worker ./worker
#login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Pushing images to Dockerhub
  - docker push haritejnarayan/multi-client
  - docker push haritejnarayan/multi-nginx
  - docker push haritejnarayan/multi-server
  - docker push haritejnarayan/multi-worker
